apiVersion: apps/v1
kind: Deployment
metadata:
  name: aml-kyc-backend
  namespace: aml-kyc-advisory
  labels:
    app: aml-kyc-backend
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aml-kyc-backend
  template:
    metadata:
      labels:
        app: aml-kyc-backend
        version: v1.0.0
    spec:
      containers:
      - name: backend
        image: aml-kyc-backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: redis-url
        - name: QDRANT_URL
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: qdrant-url
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: kafka-brokers
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: aml-kyc-secrets
              key: encryption-key
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service:11434"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aml-kyc-backend-service
  namespace: aml-kyc-advisory
  labels:
    app: aml-kyc-backend
spec:
  selector:
    app: aml-kyc-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aml-kyc-backend-hpa
  namespace: aml-kyc-advisory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aml-kyc-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

