apiVersion: v1
kind: Namespace
metadata:
  name: aml-kyc-advisory
  labels:
    name: aml-kyc-advisory
    environment: production
    app: aml-kyc-advisory
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aml-kyc-advisory-quota
  namespace: aml-kyc-advisory
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: aml-kyc-advisory-limits
  namespace: aml-kyc-advisory
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container

