# Production Kubernetes Security Policies - Secrets Management
# Comprehensive secrets management for AML-KYC Agent deployment

---
# Secret for AML Backend Database
apiVersion: v1
kind: Secret
metadata:
  name: aml-backend-db-secret
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-backend
    app.kubernetes.io/component: database
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Database credentials for AML backend"
    security.aml.io/rotation-policy: "30-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  username: YW1sX2JhY2tlbmQ=  # aml_backend
  password: YW1sX2JhY2tlbmRfcGFzc3dvcmQ=  # aml_backend_password
  host: bG9jYWxob3N0  # localhost
  port: NTQzMg==  # 5432
  database: YW1sX2t5Y19hZ2VudA==  # aml_kyc_agent

---
# Secret for AML Backend API Keys
apiVersion: v1
kind: Secret
metadata:
  name: aml-backend-api-keys
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-backend
    app.kubernetes.io/component: api
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "API keys for AML backend services"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  openrouter-api-key: b3BlbnJvdXRlcl9hcGlfa2V5  # openrouter_api_key
  prometheus-api-key: cHJvbWV0aGV1c19hcGlfa2V5  # prometheus_api_key
  grafana-api-key: Z3JhZmFuYV9hcGlfa2V5  # grafana_api_key
  elasticsearch-api-key: ZWxhc3RpY3NlYXJjaF9hcGlfa2V5  # elasticsearch_api_key
  jaeger-api-key: amFlZ2VyX2FwaV9rZXk=  # jaeger_api_key

---
# Secret for AML Frontend
apiVersion: v1
kind: Secret
metadata:
  name: aml-frontend-secret
  namespace: aml-frontend
  labels:
    app.kubernetes.io/name: aml-frontend
    app.kubernetes.io/component: frontend
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "internal"
  annotations:
    security.aml.io/description: "Frontend configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  session-secret: c2Vzc2lvbl9zZWNyZXQ=  # session_secret
  csrf-secret: Y3NyZl9zZWNyZXQ=  # csrf_secret
  api-endpoint: aHR0cDovL2FtbC1iYWNrZW5kOjgwODA=  # http://aml-backend:8080

---
# Secret for AML KYC Agent
apiVersion: v1
kind: Secret
metadata:
  name: aml-kyc-agent-secret
  namespace: aml-kyc-agent
  labels:
    app.kubernetes.io/name: aml-kyc-agent
    app.kubernetes.io/component: agent
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "KYC agent configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  llm-api-key: bGxtX2FwaV9rZXk=  # llm_api_key
  sanctions-api-key: c2FuY3Rpb25zX2FwaV9rZXk=  # sanctions_api_key
  regulatory-api-key: cmVndWxhdG9yeV9hcGlfa2V5  # regulatory_api_key
  compliance-api-key: Y29tcGxpYW5jZV9hcGlfa2V5  # compliance_api_key

---
# Secret for Monitoring
apiVersion: v1
kind: Secret
metadata:
  name: aml-monitoring-secret
  namespace: aml-monitoring
  labels:
    app.kubernetes.io/name: aml-monitoring
    app.kubernetes.io/component: monitoring
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "internal"
  annotations:
    security.aml.io/description: "Monitoring configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  prometheus-config: cHJvbWV0aGV1c19jb25maWc=  # prometheus_config
  grafana-config: Z3JhZmFuYV9jb25maWc=  # grafana_config
  elasticsearch-config: ZWxhc3RpY3NlYXJjaF9jb25maWc=  # elasticsearch_config
  jaeger-config: amFlZ2VyX2NvbmZpZw==  # jaeger_config

---
# Secret for Security Tools
apiVersion: v1
kind: Secret
metadata:
  name: aml-security-tools-secret
  namespace: aml-kyc-agent
  labels:
    app.kubernetes.io/name: aml-security-tools
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Security tools configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  falco-config: ZmFsY29fY29uZmln  # falco_config
  trivy-config: dHJpdnlfY29uZmln  # trivy_config
  kube-bench-config: a3ViZS1iZW5jaF9jb25maWc=  # kube-bench_config
  kube-hunter-config: a3ViZS1odW50ZXJfY29uZmln  # kube-hunter_config

---
# Secret for Compliance Tools
apiVersion: v1
kind: Secret
metadata:
  name: aml-compliance-tools-secret
  namespace: aml-kyc-agent
  labels:
    app.kubernetes.io/name: aml-compliance-tools
    app.kubernetes.io/component: compliance
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Compliance tools configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  nist-csf-config: bmlzdC1jc2ZfY29uZmln  # nist-csf_config
  oscal-config: b3NjYWxfY29uZmln  # oscal_config
  openscap-config: b3BlbnNjYXBfY29uZmln  # openscap_config
  compliance-api-key: Y29tcGxpYW5jZV9hcGlfa2V5  # compliance_api_key

---
# Secret for TLS Certificates
apiVersion: v1
kind: Secret
metadata:
  name: aml-tls-secret
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-tls
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "TLS certificates for AML services"
    security.aml.io/rotation-policy: "365-days"
    security.aml.io/encryption: "AES-256"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key

---
# Secret for JWT Tokens
apiVersion: v1
kind: Secret
metadata:
  name: aml-jwt-secret
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-jwt
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "JWT signing keys for AML services"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  jwt-secret: amF3dF9zZWNyZXQ=  # jwt_secret
  refresh-secret: cmVmcmVzaF9zZWNyZXQ=  # refresh_secret
  access-secret: YWNjZXNzX3NlY3JldA==  # access_secret

---
# Secret for Encryption Keys
apiVersion: v1
kind: Secret
metadata:
  name: aml-encryption-keys
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-encryption
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Encryption keys for AML data"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  data-encryption-key: ZGF0YV9lbmNyeXB0aW9uX2tleQ==  # data_encryption_key
  field-encryption-key: ZmllbGRfZW5jcnlwdGlvbl9rZXk=  # field_encryption_key
  backup-encryption-key: YmFja3VwX2VuY3J5cHRpb25fa2V5  # backup_encryption_key

---
# Secret for External API Keys
apiVersion: v1
kind: Secret
metadata:
  name: aml-external-api-keys
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-external-api
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "External API keys for AML services"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  openai-api-key: b3BlbmFpX2FwaV9rZXk=  # openai_api_key
  anthropic-api-key: YW50aHJvcGljX2FwaV9rZXk=  # anthropic_api_key
  cohere-api-key: Y29oZXJlX2FwaV9rZXk=  # cohere_api_key
  huggingface-api-key: aHVnZ2luZ2ZhY2VfYXBpX2tleQ==  # huggingface_api_key

---
# Secret for Database Encryption
apiVersion: v1
kind: Secret
metadata:
  name: aml-db-encryption-keys
  namespace: aml-backend
  labels:
    app.kubernetes.io/name: aml-db-encryption
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Database encryption keys for AML data"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  db-encryption-key: ZGJfZW5jcnlwdGlvbl9rZXk=  # db_encryption_key
  db-master-key: ZGJfbWFzdGVyX2tleQ==  # db_master_key
  db-backup-key: ZGJfYmFja3VwX2tleQ==  # db_backup_key

---
# Secret for Service Mesh
apiVersion: v1
kind: Secret
metadata:
  name: aml-service-mesh-secret
  namespace: istio-system
  labels:
    app.kubernetes.io/name: aml-service-mesh
    app.kubernetes.io/component: security
    security.aml.io/compliance: "nist-csf"
    security.aml.io/data-classification: "confidential"
  annotations:
    security.aml.io/description: "Service mesh configuration and secrets"
    security.aml.io/rotation-policy: "90-days"
    security.aml.io/encryption: "AES-256"
type: Opaque
data:
  istio-config: aXN0aW9fY29uZmln  # istio_config
  envoy-config: ZW52b3lfY29uZmln  # envoy_config
  pilot-config: cGlsb3RfY29uZmln  # pilot_config
  citadel-config: Y2l0YWRlbF9jb25maWc=  # citadel_config
